[package]
name = "y2024d13"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y2024d13"
path = "src/13.rs"

[dependencies]
derive_more = { workspace = true, features = ["deref"] }
num = { workspace = true }
parse-display.workspace = true
parse-display-with.workspace = true
