[workspace]
resolver = "3"

members = [
    "bag",
    "direction",
    "point",
    "position",
    "2023/*",
    "2024/*",
    "2024/17/bytecode-derive",
    "2024/17/bytecode",
    "2025/*",
]

[workspace.dependencies]
derive_more = "2"
enum-iterator = "2"
game-grid = "0"
itertools = "0"
lazy-regex = "3"
nom = "8"
num = "0"
parse-display = "0"
parse-display-with = "0"
pathfinding = "4"
regex = "1"
bag.path = "bag"
direction.path = "direction"
point.path = "point"
position.path = "position"
