[package]
name = "y2024d11"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y2024d11"
path = "src/11.rs"

[dependencies]
bag.workspace = true
derive_more = { workspace = true, features = ["deref"] }
parse-display.workspace = true
parse-display-with.workspace = true
