[package]
name = "y2024d21"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-iterator = "2.1.0"
# itertools.workspace = true
parse-display.workspace = true
parse-display-with.workspace = true
pathfinding.workspace = true
