[package]
name = "y2024d07"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y2024d07"
path = "src/07.rs"

[dependencies]
num = { workspace = true }
parse-display = { workspace = true }
parse-display-with = { workspace = true }
