[package]
name = "y2024d15"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true, features = ["try_from"] }
game-grid.workspace = true
parse-display.workspace = true
parse-display-with.workspace = true
