[package]
name = "y2024d06"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y2024d06"
path = "src/06.rs"

[dependencies]
derive_more = { workspace = true, features = ["deref", "deref_mut", "from_str"] }
direction.workspace = true
game-grid.workspace = true
position.workspace = true
