[package]
name = "y2024d14"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y2024d14"
path = "src/14.rs"

[dependencies]
grid = "0.16.1"
itertools = { workspace = true }
num-traits = "0.2.19"
parse-display.workspace = true
parse-display-with.workspace = true
